version: '3.8'

services:
  web:
    build: .
    ports:
      - 8080:8080
    #volumes:
    #  - .:/blogapi
    depends_on:
      - postgres
    #env_file: .env

  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - /opt/postgres/configapi:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blogapi
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: postgres 